require:
  - rubocop-packaging
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.5
  NewCops: disable

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/TrailingWhitespace:
  AllowInHeredoc: true
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true
  Keywords: [INFO, TODO, FIXME, OPTIMIZE, HACK, REVIEW, NOTE]

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: true

Naming/VariableNumber:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/Lambda:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false
  Max: 5

Naming/MethodParameterName:
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/EmptyLineAfterExample:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: true

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Lint/MissingSuper:
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/wavix-sdk-ruby.rb
